### ISSUE TITLE
Feat: Item Navigation -> Only Show "Active" items by default

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp#126]
With the introduction of the bottom nav in #125 the MVP now looks like this:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/194400/184329430-628d642b-d994-496c-9ffe-1472ab046eff.png">

By `default`, **`All`** `items` are displayed on the home page.
This is undesirable because it makes the default UI/UX cluttered. 

As a person wanting to be focussed on their current task by `default`,
I want to only see the **`Active`** `items` until I click to see the rest.

When I'm logged in, I have a few archived `items` and the issue is more clear:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/194400/184324569-f634a515-1c2e-474c-948d-9c34b9c4db7c.png">

<img width="845" alt="image" src="https://user-images.githubusercontent.com/194400/184324601-89fef9dc-220e-4b28-a534-18ec54ba75a5.png">

# Todo

+ [x] Make **`Active`** `item` visible by `default` (_not **`All`**_)
+ [x] Only show the nav once there are items i.e. hide until `items > 0`
+ [x] Highlight the current/selected nav item
+ [x] Update the appearance of the nav to look like buttons.

**Comment by SimonLab** [comment]
Current footer in PR #127 :
![image](https://user-images.githubusercontent.com/6057298/184445592-6443c59f-2dc4-4873-9ca8-7534683cca8c.png)

I haven't implemented "Only show the nav once there are items i.e. hide until items > 1" as I think it can be useful to be able to select another filter when there are not items in the current filter selected. This avoid us to have to reload the page or remove the filter manually from the url.

Another filter we could add is `running` (or somthing similar) to display only the items with a running timer (future feature)

**Comment by nelsonic** [comment]
Displaying the footer filter buttons when there are no items is a source of confusion to a new `person`. 🤷‍♂️ 
> "_What do these buttons do? Oh, nothing._" 🙄 
(when there are no items, the filters don't work. so we shouldn't display them)

Hiding the footer nav when there are no items ~~is~~ _was_ **3 lines** of code so, I implemented it. ✅ 

Decluttered:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/194400/184522553-f9a90e8c-b754-4b96-8128-919c52697fcc.png">

**Comment by nelsonic** [comment]
The reason we don't show the footer nav until `items > 1` is that we are _guiding_ the person to perform a specific action in the UI/UX. We want them to `Start` or `Stop` working on the task they have defined:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/194400/184522678-207252fb-f675-4a41-adc8-fc15e0ac3c96.png">

They don't need to _know_ about filtering `items` until _after_ they _have_ `items` to filter.
i.e. don't _distract_ the person from performing their action.

**Comment by nelsonic** [comment]
https://github.com/dwyl/app-mvp/blob/4e21db158e2d73f54c69cc7dbba6d0c649ffe830/lib/app/item.ex#L113-L124

and

https://github.com/dwyl/app-mvp/blob/4e21db158e2d73f54c69cc7dbba6d0c649ffe830/lib/app/item.ex#L126-L137

are _almost_ identical ... 💭 

So I DRYed it. ✂️

**Comment by nelsonic** [comment]
Note: filtering the `items` in `Elixir` is not very efficient from a Data-on-the-wire perspective. 
It's basically sending **_all_ `items`** between `Postgres` and `Phoenix` each time 
and then discarding ones we don't want to display ... 
We will need to do this using `Ecto` in the _actual_ App to reduce this internal bandwidth.
But let's cross that bridge when we _need_ to: https://community.fly.io/t/high-internal-bandwidth-usage/3577

**Comment by nelsonic** [comment]
Current UX: 

![only-show-footer-nav-when-items-1](https://user-images.githubusercontent.com/194400/184524490-c9b9c7ab-745b-494f-a800-11044be5d9e7.gif)
