### ISSUE TITLE
Chore: Improve initial page load time

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp#128]
At present, [PageSpeed Insights](https://pagespeed.web.dev/) tells us that the performance of the MVP is "**100**" 
https://pagespeed.web.dev/report?url=https%3A%2F%2Fmvp.fly.dev%2F  ... 💯 🤷‍♂️ 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/194400/184469983-536b61e5-6181-4008-b560-0fc4bb4db54c.png">

### **`1.9 s` Time to Interactive** 🐌 

Apparently an App that takes **`1.9 s` Time to Interactive** scores a 100 on PageSpeed.
Maybe compared to some ridiculously slow-to-load news site this is good. 
But just to render a list of `items`? it seems **_incredibly_ slow** to me. 
What can we do to lower this to **`~400ms`** on a 3G connection?
Can we pre-render and cache the page and differ connecting to the `LiveView` socket? 💭 

# Todo

+ [ ] Investigate / understand (document!) what are the main causes for "slow" page load time in a `LiveView` App. 🔍 📝 

+ [ ] _Explore_ optimising/indexing/caching the `items_with_timers/1` SQL query. 
https://github.com/dwyl/app-mvp/blob/4e21db158e2d73f54c69cc7dbba6d0c649ffe830/lib/app/item.ex#L113-L119
  + [ ] _First_ figure out how to benchmark the query with a decent amount of data e.g. 10k `items` x 10k `items`  (100M records)
    > If this feels like "_way too much_" for our little MVP, that's because it is! But it's a useful **_engineering_ exercise**. 
  + [ ] Study + write-up what we would need to do from a `Postgres` perspective to optimise the query / load time.

+ [ ] _Explore_ using Caching to speed up the initial page load for new people visiting the MVP,
e.g: https://fullstackphoenix.com/quick_tips/liveview-caching `<|` https://github.com/whitfin/cachex

+ [ ] What ***`else`*** can we do to speed up the _initial_ **Time to interactive**? 💭 

Remember the purpose of the MVP is ***Learning***.
Both our _own_ learning of how to build Apps using [**`PETAL`**](https://github.com/dwyl/technology-stack/issues/87) 👩‍💻 
and testing our _hypothesis_ that people _want_ to use a UX-focussed tool to maximise their personal effectiveness. ❤️ ✅ 
In our quest to test that hypothesis, we need to minimise the page load time ⏳ 
***So that*** the person viewing the MVP for the _first_ time is pleasantly surprised 😍 
and _we_ know we've done _everything_ we can to [**_Never_ Waste Anyone's Time**<sup>TM</sup>](https://github.com/dwyl/start-here/blob/63468a6bc020f88c762465823da7419478f29687/manifesto.md#your-time-should-never-be-wasted) 👌

**Comment by nelsonic** [comment]
@SimonLab want to pick this up and write-up a `perf.md` with your quest? 💭 
If we could shave off _any_ time from the "**Time to Interactive**" 🐌 it would be amaze! 🤞

**Comment by nelsonic** [comment]
Latest result: https://pagespeed.web.dev/report?url=https%3A%2F%2Fmvp.fly.dev%2F
![image](https://user-images.githubusercontent.com/194400/184605333-8fbce059-b40b-4705-b4fb-c7f42d14fa86.png)

The **speed index** has increased significantly. 🤷‍♂️ 
I think we need to re-think the rendering of the home page and cache it all for people who have never interacted with the app before. 💭

**Comment by SimonLab** [comment]
Current metrics on my side
![image](https://user-images.githubusercontent.com/6057298/184607127-af59fae5-6d32-45e2-b1a0-f6ae1f7389b8.png)

**Comment by nelsonic** [comment]
Yeah, similar on my side:

![image](https://user-images.githubusercontent.com/194400/184607346-2ac2f651-fa23-49b3-a6d2-95baf47a65dd.png)

this is "_acceptable_" for a web app. 💭 
It would be awesome if we could integrate this check into our CI/CD pipeline.

**Comment by nelsonic** [comment]
Accessibility and "Best Practices" have both declined to **`79`** and **`83`** respectively:
https://pagespeed.web.dev/report?url=https%3A%2F%2Fmvp.fly.dev%2F
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/194400/204009382-cd9b5563-42d3-4aab-9666-e4614ed6db8f.png">

Looks like we can tidy up the markup:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/194400/204009882-571a7de7-41f1-4521-80af-8b31b04a1558.png">

Who wants to pick this up on Monday? 🙏
