### ISSUE TITLE
EPIC: Update MVP App to Latest `Phoenix` with `auth_plug`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp#89]
This project is a bit out-of-date. 
Let's _fix_ that and add @dependabot to keep it up-to-date! 

# Todo

+ [x] Create ERD https://github.com/dwyl/app-mvp-phoenix/issues/89#issuecomment-1183866847
+ [x] Map out all existing functions/functionality [read through the docs + update!] https://github.com/dwyl/app-mvp-phoenix/issues/89#issuecomment-1165196239
+ [x] Create a branch
+ [x] Nuke all the code! 🙊 
+ [x] Create a `new` `Phoenix@1.6.10` project 🆕 
+ [x] Re-create the schemas as per the ERD 
  + [x] _Simplify_ them along the way! 
+ [x] Add `auth_plug` so we leverage `auth` from the start. https://github.com/dwyl/app-mvp-phoenix/issues/104
  + [x] `auth` is _not_ required to create items. i.e _optional_. 
+ [x] dwyl/app-mvp-phoenix#100
  + [x] create an `item` using basic interface
  + [x] `items` are automatically added to a _single_ list (separate lists can follow later)
  + [x] all `items` are considered to be `tasks` for now and thus have a timer (start) button next to them in the UI/UX
  + [x] Render counting timer using Alpine.js dwyl/app-mvp-phoenix#99 
  + [x] Accumulate timers dwyl/app-mvp-phoenix#103
  + [x] Edit `timer.text` dwyl/app-mvp-phoenix#102
  + [x] Add icons to buttons dwyl/app-mvp-phoenix#101 
  + [x] sync to connected devices
+ [x] Android/Apple Shortcut icons (for add to home screen) #111
+ [x] Create PR! https://github.com/dwyl/app-mvp-phoenix/pull/90
+ [x] Deploy to Fly.io (fast!) https://github.com/dwyl/app-mvp-phoenix/issues/109 🚀 
+ [x] Rename `timer.end` to `timer.stop`: #114 
+ [x] Implement `upsert_people/1` function #115 to `create` or `update` a `person` record. https://github.com/dwyl/app-mvp/commit/c77d43af28fa3df04c2f711a37af0e1b31afc151
+ [x] ***`DELETE`*** `people` schema/table from the project! #118 
+ [x] Update the `README.md`
  + [x] Add _brief_ section on MVPs #91 
+ [x] Assign to Simon
+ [x] Iterate!! > GOTO: #119

**Comment by nelsonic** [comment]
**`ERD`** of _existing_ MVP on `main` branch: [click the image to 

![image](https://user-images.githubusercontent.com/194400/175084956-0aa9c997-a65b-4688-92fb-19f5126064c0.png)

This ERD covers the "**_Single_ Player Mode**" described in the [/dwyl/product-roadmap#1-single-player](https://github.com/dwyl/product-roadmap/tree/c3493258d0355ba2cb04d4ed61052483f49d5f8b#1-individual-person-experience---single-player)
i.e. there is no concept of sharing, permissions or _collaboration_. 

Do we _want_ to add the complexity of "**_Multi_-Player**" to the MVP? 
I know that _personally_ I want to be able to ***`share`*** an item with my co-worker/family-member/friend etc. 
But the question is: should we be thinking about that in MVP or only in a subsequent iteration? 💭

**Comment by nelsonic** [comment]
I think I answered my _own_ question in the Product Roadmap link above. 💭 
Specifically, the App _must_ be _immediately_ useful to the _individual_ person. 👩‍💻 
So that's what I'm (_we're_) going to focus on _first_. 🏁 

And then we can add the concept of **`groups`** of (one ore more) **`people`** _later_. 👪

**Comment by nelsonic** [comment]
For reference, at the time of writing, visiting: https://dwylapp.herokuapp.com I see:
![image](https://user-images.githubusercontent.com/194400/175464832-629ffdb1-f9ed-4073-8d7a-c1c2eb464881.png)

When I authenticate with my Google Account, I see:
https://dwylapp.herokuapp.com/people/info
![image](https://user-images.githubusercontent.com/194400/175464745-b1fc4c9c-186e-48fa-adbf-fe111fe92bb5.png)

And when I click on "capture" I see: https://dwylapp.herokuapp.com/capture/new

![image](https://user-images.githubusercontent.com/194400/175464926-a84e7bb7-5a54-4b78-a0bc-05bd55462429.png)

When I submit I'm shown: https://dwylapp.herokuapp.com/categorise

![image](https://user-images.githubusercontent.com/194400/175465041-d25ebf76-ffa8-490f-972e-49accdcb8af9.png)

When visiting the list: https://dwylapp.herokuapp.com/items
![image](https://user-images.githubusercontent.com/194400/175465110-b7fc4a49-ba74-439d-933a-c82f34410c42.png)

This `item` created by a random person: https://dwylapp.herokuapp.com/items/233
![image](https://user-images.githubusercontent.com/194400/175465237-a88fb5a4-d6a3-4367-b418-4f62e86419a7.png)

Summarises it well. 💭

**Comment by nelsonic** [comment]
Quick walkthrough of the "User Journey" through using the _current_ version of the App,
with reference to the ERD:

![mvp-erd](https://user-images.githubusercontent.com/194400/175084956-0aa9c997-a65b-4688-92fb-19f5126064c0.png)

This version does not allow people to create `items` without being authenticated.
So that's the first step as noted in the screenshots above.

Once authenticated the **`person`** creates an **`item`**.
The `item` can be edited/updated.
That's it.

At present the _schema_ is there for `lists` and `list_items` but 
also the schema is there for `timers` but the _functionality/UI_ to `start|stop` a timer is not https://github.com/dwyl/app-mvp-phoenix/issues/7
`tags` and `status` tables are also present but there is no UI to manage them. 

So the MVP as it stands is _very_ incomplete. 
Let's ***fix*** that!

**Comment by nelsonic** [comment]
Dependencies we want to bring with us:

```elixir
  # Easily Encrypt Senstive Data: github.com/dwyl/fields
  {:fields, "~> 2.7.1"},
  # Auth with ONE Environment Variable: github.com/dwyl/auth_plug
  {:auth_plug, "~> 1.2.3"},
  # Useful functions: https://github.com/dwyl/useful
  {:useful, "~> 0.1.0"},

  # create docs on localhost by running "mix docs"
  {:ex_doc, "~> 0.22.6", only: :dev, runtime: false},
  # track test coverage
  {:excoveralls, "~> 0.13.2", only: [:test, :dev]},
  # git pre-commit hook runs tests before allowing commits
  {:pre_commit, "~> 0.3.4"},
  {:credo, "~> 1.1.0", only: [:dev, :test], runtime: false},
```

https://github.com/dwyl/app-mvp-phoenix/blob/745c7e87b42f07888edfe7f4527998b827e6a6e3/mix.exs#L54-L67

Note: all of these are _way_ out-of-date, this is just for reference.

**Comment by nelsonic** [comment]
Also want to keep these settings
```elixir
test_coverage: [tool: ExCoveralls],
preferred_cli_env: [
  c: :test,
  coveralls: :test,
  "coveralls.json": :test,
  "coveralls.html": :test,
  t: :test
]
```


and aliases:
```elixir
c: ["coveralls.html"],
s: ["phx.server"],
t: ["test"],
```

**Comment by nelsonic** [comment]
After re-creating the schemas using `mix phx.gen.html` and seeing how _much_ boilerplate is created: 🙄 
https://github.com/dwyl/app-mvp-phoenix/pull/90/commits/c649808721bfbd897b4541d41fc4b765dfc710a3#diff-cab907b32323b028d11c4fee542909f1fe80ccc79e7209919124998463939fe9

I decided to **`delete`** it all and try a more lightweight approach. 💭

**Comment by nelsonic** [comment]
The problem with using `mix phx.gen.schema` is that no _tests_ are created so we end up with:

```sh
Finished in 0.1 seconds (0.07s async, 0.07s sync)
3 tests, 0 failures

Randomized with seed 935707
----------------
COV    FILE                                        LINES RELEVANT   MISSED
  0.0% lib/app/item.ex                                19        2        2
  0.0% lib/app/list.ex                                20        2        2
  0.0% lib/app/person.ex                              23        2        2
  0.0% lib/app/status.ex                              17        2        2
  0.0% lib/app/tag.ex                                 17        2        2
  0.0% lib/app/timer.ex                               20        2        2
100.0% lib/app_web/controllers/page_controller.        7        1        0
100.0% lib/app_web/router.ex                          21        2        0
100.0% lib/app_web/views/error_view.ex                16        1        0
  0.0% lib/app_web/views/layout_view.ex                7        0        0
  0.0% lib/app_web/views/page_view.ex                  3        0        0
[TOTAL]  25.0%
----------------
Generating report...
```

**Comment by nelsonic** [comment]
```
13 files changed, 219 insertions(+)
```
_way_ more sane! 💭

**Comment by nelsonic** [comment]
GitHub CI will fail because the coverage threshold defined in `coveralls.json` is **`100%`**  💯 
and with these new schemas the coverage drops to **`25%`** 😮 

So need to write some tests before this will pass. 👨‍💻

**Comment by nelsonic** [comment]
Confirmed. Tests pass but coverage dropped to **`25`**:
https://github.com/dwyl/app-mvp-phoenix/runs/7088823860

![image](https://user-images.githubusercontent.com/194400/176134676-2e49e815-2d51-4fbd-b7e2-7efc826cfb74.png)

Might take a while to get this back up to **`100%`** ... ⏳ 
But, as you know, I think it's worth the effort. 💭

**Comment by SimonLab** [comment]
I'm going to look today at adding tests to boost the coverage.
confirm that running `mix c` returns the following report:
![image](https://user-images.githubusercontent.com/6057298/176416557-00fc7f93-9837-4951-abe1-ad807f52ea91.png)

**Comment by nelsonic** [comment]
Removing lists for now.
Will re-add them later on in the log.

```
mix phx.gen.schema List lists title:string person_id:references:people status:references:status tag:references:tags
```

Just that they aren't explained anywhere and it's going to be less confusing to people if we introduce the topic later!

**Comment by nelsonic** [comment]
### 2.1 Create `list_items`

```
mix ecto.gen.migration create_list_items_association
```

**Comment by nelsonic** [comment]
+ `list`<sup>3</sup> - a collection of items
  + `id`: `Int`<sup>1</sup>
  + `title`: `String` - e.g: "_Alex's Todo List_"
  + `order`: `Int` - Enum ["alphabetical", "date", "priority", "unordered"]
  + `status`: `Int` (**FK** `status.id`)

+ `list_items`
  + `item_id` (FK item.id)
  + `list_id` (FK list.id)
  + `inserted_at`

**Comment by nelsonic** [comment]
Simplified ERD:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/194400/176990183-250324ba-61ea-4434-9c68-5371ce2230c6.png">

**Comment by nelsonic** [comment]
On re-re-re-re-re-re-re-re-reading ... 📖 👀 
It doesn't make sense to introduce `tags` before the UI/UX is there either. 💭 
so removing them _temporarily_ ... ✂️ 

Re-create:
```sh
mix phx.gen.schema Tag tags text:string
```


#### `tag`

`tag` - _tags_<sup>2</sup> can be applied 
to an `item` to ***Categorise*** it.

+ `id`: `Int`
+ `inserted_at`: `Timestamp`
+ `updated_at`: `Timestamp`
+ `person_id`: `Int` (**FK** `person.id` -
    the person who defined or last updated the `tag.text`)
+ `text`: `String` - examples:
  + "note"
  + "task"
  + "checklist"
  + "reading"
  + "shopping"
  + "exercise"
  + ["reminder"](https://github.com/nelsonic/time-mvp-phoenix/issues/5)
  + "quote"
  + "memo" - https://en.wikipedia.org/wiki/Memorandum
  + "image" - a link to an image stored on a file system (e.g: IPFS or S3)
  + "author" - in the case of a book author

**Comment by nelsonic** [comment]
<sup>2</sup> We expect (_and will encourage_) people to define their own tags.
When creating tags, the UI will [_auto-suggest_](https://github.com/dwyl/app/issues/224) existing (public/curated) tags to avoid duplication and noise. For now we only need "task". <br />

**Comment by nelsonic** [comment]
Final simplification? 💭 
<img width="873" alt="image" src="https://user-images.githubusercontent.com/194400/177001882-209907ec-bd72-4dd5-807e-84566d230ad8.png">

**Comment by nelsonic** [comment]
Removed the schema migrations from the ERD to declutter:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/194400/177014286-cefc55e8-510f-44dd-befb-59f6e3315fd7.png">

Feel like this is the _final_ simplification ... 
I mean we could start with just `items` ...
But we have that in the https://github.com/dwyl/phoenix-liveview-todo-list-tutorial already.
This is meant to take it to the next level.

**Comment by nelsonic** [comment]
```md
### 2.1 Create `item_tags` Association

An `item` should be able 
to have one or more tags associated with it.
To enable this we need a new table 
to store the data.



#### `item_tags`

`item_tags` - are the `tags` applied to an `item`. 
  
+ `item_id` (**FK** item.id)
+ `tag_id` (**FK** tag.id)
+ `inserted_at`

```

**Comment by nelsonic** [comment]
Removed this chunk:



We now need to add `person_id` to `tags` and `status`
to ensure that a human has ownership over those records.


```sh
mix ecto.gen.migration add_person_id_to_tag
mix ecto.gen.migration add_person_id_to_status
```


Code additions:
+ Add `person_id` to `tags`:
[1dc6630](https://github.com/dwyl/app-mvp-phoenix/pull/18/commits/1dc66303e3ee23bec3dfc1bac87a9c7b80db964a)
+ Add `person_id` to `status`:
[4685a91](https://github.com/dwyl/app-mvp-phoenix/pull/18/commits/4685a911b4af5bf4e2bd4e934af2237ba966bcb4)

ER Diagram With the `person_id` field
added to the `tags` and `status` tables:

![app-er-diagram-person_id-status-kind](https://user-images.githubusercontent.com/194400/68773176-04a89300-0623-11ea-94fa-eff32acc4724.png)


### Associate Items with a List

An item will always be on a list even if the list only has one item.
By `default` the list an item will be associated with is "uncategorised".

Let's create the migration to link `items` to `lists`:

```
mix ecto.gen.migration create_list_items_association
```

With the migration file we need to edit the following files:

Open the `lib/app/ctx/item.ex` file, locate the `schema` block:
```elixir
schema "items" do
  field :text, :string
  field :human_id, :id
  field :status, :id

  timestamps()
end
```

Add the line `belongs_to :list, App.Ctx.List`
such that your `schema` now looks like this:

```elixir
schema "items" do
  field :text, :string
  field :human_id, :id
  field :status, :id
  belongs_to :list, App.Ctx.List # an item can be linked to a list

  timestamps()
end
```


Open the `lib/app/ctx/list.ex` file
and locate the `schema` block.
Add the line `has_many :items, App.Ctx.Item`
such that your `schema` now looks like this:

```diff
  schema "lists" do
    field :title, :string
    field :person_id, :id
    field :status, :id
+   has_many :items, App.Ctx.Item # lists have one or more items

    timestamps()
  end
```

Open the newly created migration file:
`priv/repo/migrations/{timestamp}_create_list_items_association.exs` <br />
and add the following code to the `change` block:
```elixir
def change do
  create table(:list_items) do
    add :item_id, references(:items)
    add :list_id, references(:lists)

    timestamps()
  end

  create unique_index(:list_items, [:item_id, :list_id])
end
```

That will create a lookup table to associate items to a list. <br />
Code snapshot:
https://github.com/nelsonic/time-mvp-phoenix/commit/935eac1251580c13b45d9341f0597e4118f1a66f


> **Note**: we are not imposing a restriction
(_at the database level_)
on how many lists an item can belong to in the `list_items` table.
The only restriction is in the `items` schema
`has_one :list, App.Ctx.List`.
But this can easily be updated to `has_many`
if/when the use case is validated.
See:
[time-mvp-phoenix/issues/12](https://github.com/nelsonic/time-mvp-phoenix/issues/12)


After saving the above files, run `mix ecto.migrate`.
Now when you view the Entity Relationship Diagram
it should look like this:

![app-er-diagram-with-list_items](https://user-images.githubusercontent.com/194400/68774230-ae3c5400-0624-11ea-8316-179c5b6eb1a4.png)
```

**Comment by nelsonic** [comment]
https://hexdocs.pm/ecto_erd/Mix.Tasks.Ecto.Gen.Erd.html
(thanks @SimonLab!)

**Comment by nelsonic** [comment]
Lame:
```sh
↳ Enum."-each/2-lists^foreach/1-0-"/2, at: lib/enum.ex:937
** (FunctionClauseError) no function clause matching in String.replace/4

    The following arguments were given to String.replace/4:

        # 1
        nil

        # 2
        "'"

        # 3
        ""

        # 4
        []

    Attempted function clauses (showing 1 out of 1):

        def replace(subject, pattern, replacement, options) when is_binary(subject) and is_binary(replacement) or is_function(replacement, 1) and is_list(options)

    (elixir 1.13.4) lib/string.ex:1477: String.replace/4
    (fields 2.9.0) lib/aes.ex:91: Fields.AES.fetch_keys/0
    (fields 2.9.0) lib/aes.ex:69: Fields.AES.get_key_id/0
    (fields 2.9.0) lib/aes.ex:34: Fields.AES.encrypt/1
    (fields 2.9.0) lib/encrypted.ex:21: Fields.Encrypted.dump/1
    (ecto 3.8.4) lib/ecto/type.ex:938: Ecto.Type.process_dumpers/3
    (ecto 3.8.4) lib/ecto/repo/schema.ex:996: Ecto.Repo.Schema.dump_field!/6
    (ecto 3.8.4) lib/ecto/repo/schema.ex:1009: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
    (stdlib 3.17.1) maps.erl:410: :maps.fold_1/3
    (ecto 3.8.4) lib/ecto/repo/schema.ex:1007: Ecto.Repo.Schema.dump_fields!/5
    (ecto 3.8.4) lib/ecto/repo/schema.ex:940: Ecto.Repo.Schema.dump_changes!/6
    (ecto 3.8.4) lib/ecto/repo/schema.ex:360: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto 3.8.4) lib/ecto/repo/schema.ex:269: Ecto.Repo.Schema.insert!/4
    (elixir 1.13.4) lib/code.ex:1183: Code.require_file/2
    (mix 1.13.4) lib/mix/tasks/run.ex:146: Mix.Tasks.Run.run/5
```

**Comment by nelsonic** [comment]
Thanks to @SimonLab this was just a matter of `MIX_ENV=dev mix compile --f` and then it worked ✅

**Comment by nelsonic** [comment]
Reading: https://tailwindcomponents.com/component/todo-list-app

**Comment by nelsonic** [comment]
This looks like a good _starting_ point:
```html
<div class="h-100 w-full flex items-center justify-center bg-teal-lightest font-sans">
	<div class="bg-white rounded shadow p-6 m-4 w-full lg:w-3/4 lg:max-w-lg">
        <div class="mb-4">
            <h1 class="text-grey-darkest">Todo List</h1>
            <div class="flex mt-4">
                <input class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker" placeholder="Add Todo">
                <button class="flex-no-shrink p-2 border-2 rounded text-teal border-teal hover:text-white hover:bg-teal">Add</button>
            </div>
        </div>
        <div>
            <div class="flex mb-4 items-center">
                <p class="w-full text-grey-darkest">Add another component to Tailwind Components</p>
                <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green border-green hover:bg-green">Done</button>
                <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
            </div>
          	<div class="flex mb-4 items-center">
                <p class="w-full line-through text-green">Submit Todo App Component to Tailwind Components</p>
                <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-grey border-grey hover:bg-grey">Not Done</button>
                <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
            </div>
        </div>
    </div>
</div>
```

But we need to adapt it quite a lot. 💭

**Comment by nelsonic** [comment]
@SimonLab as discussed on our pairing session, the functionality of the initial `item.create`, `toggle` & `delete` is working:

<img width="801" alt="Screenshot 2022-07-06 at 12 05 02" src="https://user-images.githubusercontent.com/194400/177536558-f935e717-d446-41e0-8119-3fedc6baa4cc.png">

But for some reason the Tailwind is not working on the inner content ... 🤦‍♂️ 

Reading: https://elixirforum.com/t/tailwind-not-working-in-production-no-styles-just-plain-html/45192/3

**Comment by nelsonic** [comment]
If we put the Todo List sample code in the `lib/app_web/templates/layout/root.html.heex` it _kinda_ works:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/194400/177537982-2530b57f-3489-44e2-9f6d-c79c73ba1a65.png">

But still none of the background colors etc. work! 😞

**Comment by nelsonic** [comment]
This is what it's _meant_ to look like:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/194400/177726043-0c6b02aa-d65d-473d-a8dd-c342edb3ac1f.png">

**Comment by nelsonic** [comment]
Looks great, right? 🙄 
![image](https://user-images.githubusercontent.com/194400/177879816-49787ab6-6f0a-43e5-a535-5d1cf1e13229.png)


More tomorrow. 🤞 

Making progress ...
![image](https://user-images.githubusercontent.com/194400/177939342-df14a947-4285-48d3-89b9-64134b95f214.png)

**Comment by nelsonic** [comment]
Making progress thanks @RobStallion's  Flex Skills 🥷
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/194400/177962628-9f7e67fc-7a41-4553-a5d1-ce716039d56a.png">

Ref: https://flexboxfroggy.com 😮

**Comment by nelsonic** [comment]
Minor progress:

![image](https://user-images.githubusercontent.com/194400/178122544-fb674a70-5393-414a-9aa7-d2b8756f1a2b.png)

**Comment by nelsonic** [comment]
Annoying side quest: https://github.com/dwyl/app-mvp-phoenix/issues/92 🙄

**Comment by nelsonic** [comment]
Very close to getting the timer working ... 🤞 

![image](https://user-images.githubusercontent.com/194400/178220712-8703ec78-9fa7-45fb-9855-b026572bab80.png)

**Comment by nelsonic** [comment]
Timer works but is a "hack" based on the fact that each time a timer is tarted a **`new`** timer is created.
This is the _desired_ behaviour. 
![mvp-timer-working](https://user-images.githubusercontent.com/194400/178250044-d2fbfbad-36e9-45b9-870f-c5cbf372ef54.gif)
But it will not work if a new client is signed into the App once a timer is running.
So we will need to re-work this soon.

**Comment by nelsonic** [comment]
Removed **`status`** schema from project:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/194400/178869576-c6aff9d7-1bc3-43ff-80ac-71b3e86363dd.png">

No associations. Still does _exactly_ what we need it to. _Muuuuch_ simpler! 🙌

**Comment by nelsonic** [comment]
Dogfooding: 😜 
![image](https://user-images.githubusercontent.com/194400/179257317-a8e2aa61-995f-4296-b589-a57e823eae68.png)

**Comment by nelsonic** [comment]
Added icons to the buttons: #101 

![image](https://user-images.githubusercontent.com/194400/179338781-5bb16621-a76b-4ca5-8abd-d0d6acfd05a8.png)

**Comment by nelsonic** [comment]
been neglecting the dev log in the **`README.md`** these last few days as I learn **`Tailwind`** (**`flex`**!) ... ⏳ 
3 more task to do:
1. #102 
2. #103 
3. #104 

Once those are done I plan to dedicate **`T4h`** to updating the **`README.md`** then will assign for review/feedback. 🤞

**Comment by nelsonic** [comment]
Auth implemented: 🚀 

![mvp-auth-implemented-2x-speed-full-quality](https://user-images.githubusercontent.com/194400/179797413-63e8de62-733f-4c57-a24d-7c0c662e7c46.gif)

**Comment by nelsonic** [comment]
This MVP is now feature complete! ref: https://github.com/dwyl/app/issues/265 🎉 
Just need to _deploy_ to Fly.io #109 🚀 
Then need to go through the `README.md` and update all the instructions. 📝 ⏳

**Comment by nelsonic** [comment]
Deployed to Fly.io https://mvp.fly.dev/ 🚀 
![image](https://user-images.githubusercontent.com/194400/179984838-3deea91f-ee73-47e8-8707-9a1e837c3719.png)

Will make a decent GIF after lunch. 👌

**Comment by nelsonic** [comment]
GIF: 
![mvp-fly-auth](https://user-images.githubusercontent.com/194400/180079997-b43a24c2-7a50-4755-aef9-ef3f2aa28816.gif)

**Comment by nelsonic** [comment]
Been re-re-re-re-re-reading the `README.md` ... 👀 
and decided to take a quick detour to rename `timer.end` to `timer.stop`:  https://github.com/dwyl/app-mvp/issues/114 🔚 
BRB! 🧑‍💻 ⏳

**Comment by nelsonic** [comment]
@SimonLab the code is _mostly_ there for the MVP. If you want to take a look at it now, please go for it. 
I've not had much focus time these last few days ... 🙄 really want to finish the `README.md` ... ⏳ 
If you want to change any part of the code, please go for it. I will reflect your updates in the `README.md` 📝 
But please avoid any large refactors. we can put those in the "_real_" App. 💭

**Comment by nelsonic** [comment]
Minor detour: https://github.com/dwyl/app-mvp/issues/115 `person` being inserted multiple times! 🤦‍♂️

**Comment by nelsonic** [comment]
Do we _need_ to have a `people` table in the MVP at all? 💭 >>  https://github.com/dwyl/app-mvp/issues/118

**Comment by nelsonic** [comment]
Removing the `people` table as discussed/concluded in: https://github.com/dwyl/app-mvp/issues/118#issuecomment-1206248882

**Comment by nelsonic** [comment]
Successfully removes `people` schema/table from the project: https://github.com/dwyl/app-mvp/commit/316929c39888ea3285f6d42324844f95231f588e ✂️ 

New ERD:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/194400/183075195-c1b50232-5988-47cb-ad18-47dfd4c0bcc3.png">

Everything still works as expected. 📝  ⏳ ✅ 
That's it! The MVP in a nutshell. Two tables.

**Comment by nelsonic** [comment]
Coverage hasn't dropped, it's just not being accurately recorded on my Mac ... 🙄 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/194400/183305279-599183e4-a9e4-4de2-864f-6d3fb69ccfae.png">

**Comment by nelsonic** [comment]
@SimonLab I've finished updating 
the `README.md`: https://github.com/dwyl/app-mvp/blob/phoenix-1.6-2022-refresh-issue-%2389/README.md 📜 
and `BUILDIT.md` dev log:  https://github.com/dwyl/app-mvp/blob/phoenix-1.6-2022-refresh-issue-%2389/BUILDIT.md  🧑‍💻 

Please take a look and give feedback when you can.  🙏 
Thanks again for your patience on this. 👍

**Comment by nelsonic** [comment]
Final **`GIF`**:
![mvp-localhost-demo](https://user-images.githubusercontent.com/194400/183337496-429af597-45a2-447f-9061-a494907736d9.gif)

**Comment by nelsonic** [comment]
After removing `people` table had to run:

```sql
ALTER TABLE items 
RENAME COLUMN status_code TO status;

DROP INDEX items_person_id_index;
ALTER TABLE items DROP CONSTRAINT items_person_id_fkey;

ALTER TABLE timers DROP CONSTRAINT timers_person_id_fkey;

DROP TABLE people;
```

**Comment by nelsonic** [comment]
@SimonLab your suggested fixes merged into the PR #90  ✅ 
Please review again when you can. 🙏

**Comment by SimonLab** [comment]
PR #90 merged, we can start the last checkbox item: `iterate`

**Comment by nelsonic** [comment]
Thanks again @SimonLab 🎉
